name: GitHub Actions Build and Deploy
on:
  push:
    paths:
      - "notebook/*.md"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'Lifeni-Site/Website'
          submodules: 'true'

      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: git submodule update --remote
      - run: yarn
      - run: yarn clean
      - run: yarn build
        env:
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: 'public'
          target: '/home/website'
          overwrite: true
